apiVersion: v1
kind: Secret
metadata:
  name: server-tls
  namespace: istio-system
type: kubernetes.io/tls
#
# Atencao!
# Isto e apenas um exemplo.
# Certificados, chaves privadas e valores sensiveis em geral nunca
# devem ser armazenados em repositorios.
# Sempre utilize um cofre de segredos (como vault ou github secrets)
# para armazenar valores sensiveis.
#
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC2DCCAcCgAwIBAgIJAM9vxpEto64PMA0GCSqGSIb3DQEBBQUAMBsxGTAXBgNV
    BAMTEG15LXNhbXBsZS1hcHAuaW8wHhcNMjEwOTI4MDAwNDMyWhcNMzEwOTI2MDAw
    NDMyWjAbMRkwFwYDVQQDExBteS1zYW1wbGUtYXBwLmlvMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAx9BxcCVOIUIQtRXezbSrq9D0RSHatScUUWAsXSco
    SdePWdY7va5LBhaPVRxPmfnHaIcuL/1MQjcsJj7yHyJavefbe7V2FZBcGWiBeUtL
    +Iy7C5is5YEMSwkGgmImC3IkLJq0N54+RcXl9pJp80BhsjSI1HGH/49CnWQ992cz
    InBOIQFKmjpOELJbKIRz6XN9ejcf62Kih5Fj8ivAZwJ1YN9JeU3qyXbvhxF360gB
    2KdADGjND68mb5uHLWsI1JFG5VRS69/lAG0VhzOhYkFPTD+HYhZBsUPX+HojnAh6
    /1AzAodhbrg+S9ra6j0JtlAWMsHH9Fbj2l88BDU70w3u2QIDAQABox8wHTAbBgNV
    HREEFDASghBteS1zYW1wbGUtYXBwLmlvMA0GCSqGSIb3DQEBBQUAA4IBAQB5tpqG
    EkQJnqRPUE+h/rlS3/QFOMtEBAtburKjURvUN4vVKIDbNqpKCRD9HgG2YNjAlp1H
    qecdjWVvh5V2BKNZH0nVy2R+Uzbrj0OD36Q84OFg+GDxtqb5cTXDJ/mkduT7YYDI
    ECs6QGpQI6p/1KGYkYGc/OF9VFqxjDMpPLg7wy8cI11FG/8dmbeZessFQXbr0Y8r
    1OHUbkHRc0GnrMe04CNA5IXpWXiYB3AIGMFfIxZUm/GICxcOzWG5IVnAS2ynUg0Q
    uzV3cwixCwcJYcislPT6jIUvjyDzhqDXYL2pRxoJz5bn2CDCajiOtJOeoyOieJv8
    sFwihS0VzANYRyPd
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAx9BxcCVOIUIQtRXezbSrq9D0RSHatScUUWAsXScoSdePWdY7
    va5LBhaPVRxPmfnHaIcuL/1MQjcsJj7yHyJavefbe7V2FZBcGWiBeUtL+Iy7C5is
    5YEMSwkGgmImC3IkLJq0N54+RcXl9pJp80BhsjSI1HGH/49CnWQ992czInBOIQFK
    mjpOELJbKIRz6XN9ejcf62Kih5Fj8ivAZwJ1YN9JeU3qyXbvhxF360gB2KdADGjN
    D68mb5uHLWsI1JFG5VRS69/lAG0VhzOhYkFPTD+HYhZBsUPX+HojnAh6/1AzAodh
    brg+S9ra6j0JtlAWMsHH9Fbj2l88BDU70w3u2QIDAQABAoIBAH7FtPMd+BAJxmfd
    1FpWwoRkMlaaQBSnErD+f6cqbNlMtlqdHZIevuLB9XZeW/KpEucyvQ8degCY2J37
    Wcp/FWtfa1V1r9HGoWhNcbfvGeg8AYA+AZQq6A3DUCnw84pXhLP4A1c2QvQpttlV
    03rN4i4aPqXq0gpGblFFhDsvcrXpww7WLxCHchc9EDagQU3cta/Kyi7e0h0U6/KQ
    9zhNR+0qDn6iX4wlKl5dJsbBzISNej6LszGpciujwRxCyOhir9jSL4xKz6yMJGhK
    fX1ziVeIPKr9fgKtqpK0wRHyrWXhLWcvxCHpRFH5YnqNfDAjexuqySy6o7DDwqrT
    KyPEjsECgYEA9FjHEhjUI1l7bbgC+WvYt8z2rdOjLyuI2VP5EgqIV8j1ZYec5VvH
    Ux95nIMBA92RC02+rFHGuEVbk/Q2vCRpr9t1Zn3GJCtCjCDg4dt3pUSSMtfixS8j
    hrFwndsTBQFBVG1K0E8kNn9AYaf4vWIpyjJf4G3YM4EtGw64hKPtBRUCgYEA0Vf4
    CSFvm4qFd5NTZsBOrUSh4ik6HN6J+dAi6J8XL8ci7d1YFDB1U9TExSUXOEJL4ExC
    Vos+7BPNdBj+Fn0a2zWx2nx350FOMOlSfax2CZ0t4hPHtiKMyu8GDSmHD6NjsKak
    Df9oDqAqV9cQkGm5nx+luPufg62lXO9X+/l3u7UCgYAbMOnuRJ8O0/1dR1XlZa/3
    PDLTQzLso96VuLeF33AuvKk6RC4cg+sZf+4rkZSCVpy2ck9eo7cGeIlpXIrewvqT
    3EsjPanYCoxcRahg2ehllsziJY4RvV4ptgM/PcrPCsW3XHYv2i7Adca3V1bh1FOs
    MZDjy7V8fcqEMU4tTISqxQKBgHGnDKYIXQtYvPUaKuFR7mTrKega8c3Sk53ofctE
    89WgizoQPU1YsZn9nYZaiKymcYMoY6uQlWydo6EwIGIdMYNpN1Gi2YXXUpgDVCGe
    i8bUaqCelIIxZ7aU5fgnX4gB8JFrJw3iZ5/pHJPr0rZUb84P5Gz1TriygWBfIKlP
    2s0xAoGAQEtT5PYYjwZ0f/OFxFhFvokAm0ysOOfIKQSe4q1hy/JBq4vuvmycMMRy
    E0fYLvjhCMY4xr8f+cxdpb83qNwEGtYlzcohqKhJCPBNADSHmEMHGP7rurcchydk
    6ZbD50dxgx2qfV9pHxOffCNf57U/zeByhJLd7xhk3gy1DK4fa+0=
    -----END RSA PRIVATE KEY-----
