apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: users
spec:
  selector:
    matchLabels:
      app: users
  jwtRules:
    - issuer: "my-auth-server.io"
      jwksUri: https://raw.githubusercontent.com/ribaptista/istio-exemplos/main/code/6-JWT/jwks/jwks.json
